version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
     - NODE_ENV=production
     - PORT=3001
    ports:
      - '8080:8080'
      - '3001:3001'
    volumes:
      - /app/node_modules
      - ./server:/app
